version: '3.8'

volumes:
  database: {}

services:
  test-database:
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - 'POSTGRES_DB=${ETH_NETWORK}'
    ports:
      - 5434:5432
